spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jeehomework?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Hongkong
    username: jeehomework
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8848